#!python
import argparse
import traceback
import ih.workflow

parser = argparse.ArgumentParser(description = "Initial setup for job submission")
parser.add_argument("--dir", dest="dir", default=".", help="Base directory name.")
parser.add_argument("--template", default="input/crawl.json", dest="template", help="Name of template file to use for directory crawling.")
parser.add_argument("--validate", dest="validate", action="store_true", help="If specified only validates the workflow.  Does not generate submission.")
args = parser.parse_args()

try:
    loader = ih.workflow.ImageLoader(args.template, args.dir, args.validate, True)
    loader.crawl()
    loader.write()
    loader._success()
except Exception as e:
    print traceback.format_exc()
