#!python
import argparse
import traceback
import ih.imgproc

parser = argparse.ArgumentParser(description = "Thresholds an image based on windows.")
parser.add_argument("--input", dest="input", help="Path to input image.")
parser.add_argument("--ksize", dest="ksize", type=int, help="Size of the kernel.  Should be odd and positive.", required = True)
parser.add_argument("--outputdir", dest="outputdir", default=".", help="Path to write output files, if not specified use current directory.")
parser.add_argument("--output", default=None, dest="output", help="Name of output image to write, if not specified, use input image name.")
parser.add_argument("--writeblank", default=False, action="store_true", help="If errors happen, write a blank file.  Used to ensure dependent files exist for pegasus workflows.")
args = parser.parse_args()

try:
    plant = ih.imgproc.Image(args.input, args.outputdir, args.output, False)
    plant.medianBlur(args.ksize)
    plant.write()
except Exception as e:
    print traceback.format_exc()
    if args.writeblank:
      with open(args.outputdir + "/" + args.output, "w") as wh:
        wh.write("not an image.")
