#!python
import argparse
import traceback
import ih.imgproc

parser = argparse.ArgumentParser(description = "Shifts colors in an image based on nearest neighbors.")
parser.add_argument("--input", dest="input", help="Path to input image.", required = True)
parser.add_argument("--spatial_radius", dest="spatial_radius", type=int, help="Spatial Radius.", required = True)
parser.add_argument("--range_radius", dest="range_radius", type=int, help="Range Radius.", required = True)
parser.add_argument("--min_density", dest="min_density", type=int, help="Minimum Density.", required = True)
parser.add_argument("--outputdir", dest="outputdir", default=".", help="Path to write output files, if not specified use current directory.")
parser.add_argument("--output", default=None, dest="output", help="Name of output image to write, if not specified, use input image name.")
parser.add_argument("--writeblank", default=False, action="store_true", help="If errors happen, write a blank file.  Used to ensure dependent files exist for pegasus workflows.")
args = parser.parse_args()

try:
    plant = ih.imgproc.Image(args.input, args.outputdir, args.output, False)
    plant.meanshift(args.spatial_radius, args.range_radius, args.min_density)
    plant.write()
except Exception as e:
    print traceback.format_exc()
    if args.writeblank:
      with open(args.outputdir + "/" + args.output, "w") as wh:
        wh.write("not an image.")
